# CANVAS SETTINGS
CANVAS_WEIGHT = 1280
CANVAS_HEIGHT = 720
CANVAS_CENTER_X = CANVAS_WEIGHT / 2
CANVAS_CENTER_Y = CANVAS_HEIGHT / 2

# PLAYER MOVEMENT SETTINGS
PIXEL_PER_METER = (10.0 / 0.3)  # 10 pixel 30 cm
RUN_SPEED_KMPH = 10.0  # Km / Hour
RUN_SPEED_MPM = (RUN_SPEED_KMPH * 1000.0 / 60.0)
RUN_SPEED_MPS = (RUN_SPEED_MPM / 60.0)
RUN_SPEED_PPS = (RUN_SPEED_MPS * PIXEL_PER_METER)

TIME_PER_ACTION = 0.5
ACTION_PER_TIME = 1.0 / TIME_PER_ACTION
FRAMES_PER_ACTION_8 = 8
FRAMES_PER_ACTION_10 = 10

PLAYER_1_GROUND = 210
PLAYER_START_LINE = 100

STAMINA_MAX = 10000

# HURDLE SETTINGS
HURDLE_CLAMP = 300
RUNNER_HURDLE_Y = 190
